package klog.format

enum class FormatConstant {
    LR_DATE_TIME, LR_UTC, NOW_DATE_TIME, NOW_UTC,
    LOG_LEVEL, LOGGER_ID, MESSAGE, THROWABLE,
    MARKER, STRING,
    CALLER_FILE, CALLER_CLASS, CALLER_METHOD, CALLER_LINE
}